import Head from 'next/head';
import { useState } from 'react';
import CardBack from '../components/CardBack';
import CardFront from '../components/CardFront';

export default function Home() {
  const [formData, setFormData] = useState({
    cardholderName: '',
    cardNumber: '',
    expMonth: '',
    expYear: '',
    cvc: '',
  });

  const onChange = (e) => {
    console.log(formData);
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const onChangeCC = (e) => {
    console.log(formData);
    setFormData({ ...formData, [e.target.name]: cc_format(e.target.value) });
  };

  function cc_format(value) {
    const v = value
      .replace(/\s+/g, '')
      .replace(/[^0-9]/gi, '')
      .substr(0, 16);
    const parts = [];

    for (let i = 0; i < v.length; i += 4) {
      parts.push(v.substr(i, 4));
    }

    return parts.length > 1 ? parts.join(' ') : value;
  }

  return (
    <div>
      <Head>
        <title>Interactive Card Details Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex flex-col md:flex-row">
          <div className="bg-[url('/assets/bg-main-mobile.png')] md:bg-[url('/assets/bg-main-desktop.png')] shrink-0 bg-cover h-64 md:h-screen md:w-96 ">
            <div className="absolute z-10 left-2 top-32 md:top-40 md:left-36">
              <CardFront
                cardNumber={formData.cardNumber}
                cardholderName={formData.cardholderName}
                expMonth={formData.expMonth}
                expYear={formData.expYear}
              />
            </div>
            <div className="absolute z-0 left-10 top-6 md:top-96 md:left-52 ">
              <CardBack cvc={formData.cvc} />
            </div>
          </div>

          {/* Form */}
          <form className="pt-20 md:pt-0 px-6  flex flex-col md:justify-center md:mx-auto md:w-[30rem]">
            {/* Input Group */}
            <div className="flex flex-col">
              <label
                htmlFor="cardholder-name"
                className=" text-very-dark-violet"
              >
                CARDHOLDER NAME
              </label>
              <input
                onChange={onChange}
                value={formData.cardholderName}
                type="text"
                name="cardholderName"
                id="cardholder-name"
                className="border-2 p-2 rounded-md mt-1 mb-4 text-dark-grayish-violet"
                placeholder="e.g. Jane Appleseed"
              />
            </div>
            {/* Input Group */}
            <div className="flex flex-col">
              <label htmlFor="card-number" className=" text-very-dark-violet">
                CARD NUMBER
              </label>
              <input
                onChange={onChangeCC}
                value={cc_format(formData.cardNumber)}
                type="text"
                name="cardNumber"
                id="card-number"
                className="border-2 p-2 rounded-md mt-1 mb-4 text-dark-grayish-violet"
                placeholder="e.g. 1234 5678 9123 0000"
              />
            </div>
            {/* Triple Input Group */}
            <div className="flex">
              {/* Column 1 */}
              <div className="w-1/2">
                <label htmlFor="" className=" text-very-dark-violet">
                  EXP. DATE (MM/YY)
                </label>
                <div className="flex">
                  <input
                    onChange={onChange}
                    value={formData.expMonth}
                    type="text"
                    name="expMonth"
                    id="exp-date-m"
                    placeholder="MM"
                    className="border-2 p-2 rounded-md mt-1 mb-4 min-w-0 mr-2 text-dark-grayish-violet"
                  />
                  <input
                    onChange={onChange}
                    value={formData.expYear}
                    type="text"
                    name="expYear"
                    id="exp-date-y"
                    placeholder="YY"
                    className="border-2 p-2 rounded-md mt-1 mb-4 min-w-0 mr-2 text-dark-grayish-violet"
                  />
                </div>
              </div>
              {/* Column 2 */}
              <div className="w-1/2">
                <div className="flex flex-col">
                  <label htmlFor="" className=" text-very-dark-violet">
                    CVC
                  </label>
                  <input
                    onChange={onChange}
                    type="text"
                    name="cvc"
                    id="cvc"
                    className="border-2 p-2 rounded-md mt-1 mb-4 text-dark-grayish-violet"
                    placeholder="e.g. 123"
                  />
                </div>
              </div>
            </div>
            <button className="bg-very-dark-violet text-white w-full p-4 rounded-lg">
              Confirm
            </button>
          </form>
        </div>
      </main>
    </div>
  );
}
